server.port=${PORT:8080}

spring.datasource.url=${postgresql://focusforge_9hc0_user:tfFrlzzAtxo3Po2kBZr0aZCDM2sYRkip@dpg-d6gr1kk50q8c73a8r7hg-a/focusforge_9hc0}
spring.datasource.username=${focusforge_9hc0_user}
spring.datasource.password=${tfFrlzzAtxo3Po2kBZr0aZCDM2sYRkip}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false