spring.application.name=focusforge
spring.datasource.url=jdbc:mysql://localhost:3306/focusforge
spring.datasource.username=root
spring.datasource.password=Aashu@121

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8082
